nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java

JIRA : https://jira.nuxeo.com/browse/NXP-17450
Related PR : https://github.com/nuxeo/nuxeo/pull/228
The TestAndPush build succeeds! https://qa.nuxeo.org/jenkins/view/All/job/TestAndPush/job/ondemand-testandpush-egiuly/lastBuild/

Fix nxp 17450 detect mime type from nuxeo registry

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/16/

fix-NXP-20405-wrong-mimetype-after-update

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-7.10/16/

fix-NXP-20405-wrong-mimetype-after-update-7.10

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-6.0/4/

fix-NXP-20405-wrong-mimetype-after-update-6.0

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/Application.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/206/

fix-NXP-22824-restapi-download-context

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/Application.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/33/

fix-NXP-22824-restapi-download-context-8.10

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav/pom.xml
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/AbstractVirtualBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SearchRootBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/service/WIRequestFilter.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/356/

cleanup-NXP-24090-replace-commons-lang-with-lang3

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/318/

cleanup-NXP-24092-code-quality-3

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/service/WIRequestFilter.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/service/WebDavService.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/319/

cleanup-NXP-24092-code-quality-4

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SearchRootBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/326/

feature-NXP-24033-nxql-is-trashed

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/378/

feature-NXP-24032-doc-model-trashed-api

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/347/

feature-NXP-24386-servlet-api-3.1

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/23/

cleanup-NXP-24366-NXP-22544-cleanup-localdeploy

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/RootResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/57/

fix-NXP-19897-webdav-8.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/RootResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/366/

fix-NXP-19897-webdav

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/RootResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-2/106/

fix-NXP-19897-webdav-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/371/

fix-NXP-24632-webdav-copy-macos

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-2/111/

fix-NXP-24632-webdav-copy-macos-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/62/

fix-NXP-24632-webdav-copy-macos-8.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-lduarte/41/

fix-NXP-24677-webdav-exception-on-move

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-lduarte-8.10/4/

fix-NXP-24677-webdav-exception-on-move-backport-8.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-lduarte-9.10/14/

fix-NXP-24677-webdav-exception-on-move-backport-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/PathCache.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/7/

fix-NXP-24508-msword-does-not-increment-version-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/PathCache.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/68/

fix-NXP-24508-msword-does-not-increment-version-8.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/PathCache.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-7.10/52/

fix-NXP-24508-msword-does-not-increment-version-7.10

---

nuxeo-webdav-test/pom.xml
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java
nuxeo-webdav-test/src/test/resources/META-INF/MANIFEST.MF
nuxeo-webdav-test/src/test/resources/OSGI-INF/servletcontainer-config.xml

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/405/

feature-NXP-24493-jetty-too-old

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-3/17/

fix-NXP-25462-webdav-rename-folder

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/22/

fix-NXP-25462-webdav-rename-folder-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/79/

fix-NXP-25462-webdav-rename-folder-8.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-7.10/55/

fix-NXP-25462-webdav-rename-folder-7.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/ExceptionHandler.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-7.10/66/

fix-NXP-25586-webdav-quota-7.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/ExceptionHandler.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/97/

fix-NXP-25586-webdav-quota-8.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/ExceptionHandler.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/38/

fix-NXP-25586-webdav-quota-9.10

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/ExceptionHandler.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/479/

fix-NXP-25586-webdav-quota

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/487/

fix-NXP-25818-webdav-tmp-cleanup

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/42/

fix-NXP-25818-webdav-tmp-cleanup-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/100/

fix-NXP-25818-webdav-tmp-cleanup-8.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-7.10/68/

fix-NXP-25818-webdav-tmp-cleanup-7.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/TestEscapeUtils.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/EscapeUtils.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/ExistingResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FileResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/FolderResource.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/resource/VirtualFolderResource.java

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/46/

fix-NXP-25684-webdav-brackets-9.10

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/AbstractServerTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/LitmusTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavServerFeature.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/606/

feature-NXP-26563-no-fixed-test-port

---

nuxeo-webdav-test/src/test/java/org/nuxeo/ecm/webdav/WebDavClientTest.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/Backend.java
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

NXP-26552 fix webdav folder rename

---

nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/backend/SimpleBackend.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/307/

fix-NXP-26178-note-double-versioning

---

nuxeo-webdav/pom.xml
nuxeo-webdav/src/main/java/org/nuxeo/ecm/webdav/service/WebDavService.java

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-3/27/

improvement-NXP-24952-compile-with-java11
